# Generated by Django 5.2.2 on 2025-06-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('stock', models.IntegerField()),
                ('store_presence', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_quantity', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
