# Generated by Django 5.2.2 on 2025-06-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
